language: vi

pipeline:
# 1. Tách từ
- name: WhitespaceTokenizer

# 2. Đặc trưng từ vựng
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer

# 3. Vector hóa (Giúp hiểu từ vựng)
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4

# 4. Phân loại
- name: DIETClassifier
  epochs: 150                   # Có thể tăng để điều chỉnh bot duyệt dữ liệu kỹ hơn
  constrain_similarities: true
  entity_recognition_mode: true

# 5. Xử lý đồng nghĩa 
- name: EntitySynonymMapper

# 6. Chọn câu trả lời
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true

# 7. Xử lý khi Bot không hiểu 
- name: FallbackClassifier
  threshold: 0.4                # Mỗi 0.1 là 10% độ chắc chắn để bot hiểu đúng ý người dùng và trả lời
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
assistant_id: 20251124-220138-dark-engineer